openapi: 3.0.3
info:
  title: SchemaCAN
  description: An open schema for specifying CAN Bus communication.
  contact:
    name: Liam Kinne
    url: https://autonomoose.technology/product/schemacan
    email: support@autonomoose.technology
  license:
    name: Mozilla Public License Version 2.0
    url: https://www.mozilla.org/en-US/MPL/2.0/
  version: 1.0.0
components:
  schemas:
    Object:
      type: object
      required:
        - version
        - type
        - metadata
      properties:
        version:
          type: string
        type:
          type: string
        metadata:
          $ref: '#/components/schemas/Metadata'
        spec:
          oneOf:
            - $ref: '#/components/schemas/SLOT'
            - $ref: '#/components/schemas/Identifier'
            - $ref: '#/components/schemas/Signal'
            - $ref: '#/components/schemas/Message'
            - $ref: '#/components/schemas/Device'
          discriminator:
            propertyName: type
    Metadata:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        namespace:
          type: string
          default: 'default'
        labels:
          type: object
          additionalProperties:
            type: string
          example:
            manufacturer: ACME Corp.
            revision: 1.2.3
    SLOT:
      description: Slots are a J1939 construct that define how real values are encoded and decoded to and from fixed-point integers.
      type: object
      properties:
        min:
          description: Minimum possible value
          type: number
          format: float
        max:
          description: Maximum possible value
          type: number
          format: float
        offset:
          description: Offset of value
          type: number
          format: float
        size:
          description: Number of bits the signal occupiess
          type: integer
          format: uint8
        unit:
          description: Unit of measurement
          type: string
    Identifier:
      type: object
      properties:
        standard:
          description: 11-bit identifier
          type: number
        extended:
          description: 29-bit identifier
          type: number
    Signal:
      type: object
      required:
        - name
      properties:
        name:
          description: Name of the signal
          type: string
        type:
          description: Number of bits the signal occupies
          type: string
        slot:
          description: Reference to a J1939 SLOT
          type: string
        padding:
          description: Number of padding bits between signals
          type: integer
          format: uint8
    Message:
      description: Messages define the details of a CAN Bus frame an the format of its data
      type: object
      required:
        - length
        - data
      properties:
        identifier:
          $ref: '#/components/schemas/Identifier'
        length:
          type: integer
          format: uint8
          default: 0
        data:
          description: Data format
          type: array
          default: []
          items:
            $ref: '#/components/schemas/Signal'
    Device:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
paths:
  /api/v1/objects:
    get:
      description: Returns all objects
      responses:
        '200':
          description: A list of objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Object'
  /api/v1/devices:
    get:
      description: Returns all message formats
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
  /api/v1/messages:
    get:
      description: Returns all message formats
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
  /api/v1/slots:
    get:
      description: Returns all SLOTs
      responses:
        '200':
          description: A list of SLOTs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SLOT'
